# Generated by Django 4.0.4 on 2022-04-22 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchData',
            fields=[
                ('index', models.IntegerField(default=0, unique=True)),
                ('title', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('channelTitle', models.CharField(default='#', max_length=1000)),
                ('desc', models.TextField()),
                ('duration', models.CharField(default='#', max_length=12)),
                ('videoURL', models.CharField(default='#', max_length=1000)),
                ('thumbURL', models.CharField(default='#', max_length=1000)),
                ('publishTime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
